name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - run: poetry install --no-interaction --no-root

      - uses: actions/setup-node@v3

      - run: npm install -g pyright

      - run: poetry run pytest --cov
