# https://jacobian.org/til/github-actions-poetry/

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - run: poetry install --no-interaction --no-root

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - run: npm install pyright --global

      - run: poetry run pytest
